### ISSUE TITLE
Ruoka-API returns HTTP 502 Bad Gateway

### ISSUE THREAD

**Issue by l3ku** [tophattom/ruoka-api#2]
When opening https://ruoka.xyz, the AJAX spinner image is never replaced by restaurant menus, because the API request returns a HTTP 502 response. Below is a screenshot from Google Chrome console:
![screen shot 2018-04-13 at 20 09 33](https://user-images.githubusercontent.com/24781811/38748427-b59ad078-3f56-11e8-8fa5-6e7fcf759aa4.png)

**Comment by tophattom** [comment]
Fixed. Btw, wrong repo. Should be in https://github.com/tophattom/ruoka.xyz
